---
ssh_keys:
  - 

timezone: 'America/Los_Angeles'

nfs_base_dir: '/mnt/nfs/netboot'
tftp_base_dir: '/mnt/nfs/netboot/tftp'
server_build_dir: '/mnt/nfs/build'

docker_apt_arch: arm64
docker_install_compose: false
docker_users:
  - pi

# kubernetes_apt_release_channel: main
# kubernetes_apt_repository: "deb http://apt.kubernetes.io/ kubernetes-xenial {{ kubernetes_apt_release_channel }}"
kubernetes_version: '1.19'
kubernetes_allow_pods_on_master: false
kubernetes_enable_web_ui: true
kubernetes_web_ui_manifest_file: https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml
kubernetes_toleration_not_ready: 300
k8s_manage_namespace: false
k8s_no_log: false
k8s_config_filename: 'config-mini-k8s'